spring:

  application:
    name: "demo"
  
  # devtools:
  #   livereload:
  #     port: 35000

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  
redis:
  port: 6379
  host: "localhost"
