services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./script.sh:/init/script.sh
    command: ["/bin/bash", "-c", "/init/script.sh"] 

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: secret
      
  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
    
  pgvector:
    image: ankane/pgvector
    container_name: pgvector
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: myuser
      POSTGRES_DB: mydatabase
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pg_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "80:80"
    networks:
      - pg_network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./root/.ollama:/root/.ollama
    networks:
      - webui_network
    devices:
      # - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm

  webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports: 
      - "3000:8080"
    volumes:
      - ./app/backend/data:/app/backend/data
      - ./root/.ollama/models:/ollama/models
    networks:
      - webui_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # chromadb:
  #   image: chromadb/chromadb:latest
  #   container_name: chromadb_server
  #   ports:
  #     - "8000:8000"
  #   restart: always

networks:
  webui_network:
    driver: bridge
  pg_network:
    driver: bridge

volumes:
  redis-insight:
  pgvector_data:
