services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./volumes/rabbitmq_data:/var/lib/rabbitmq
      - ./script.sh:/init/script.sh
    command: ["/bin/bash", "-c", "/init/script.sh"]

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: secret
    volumes:
      - ./volumes/redis_data:/data

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - "5540:5540"

  pgvector:
    image: ankane/pgvector
    container_name: pgvector
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./volumes/pgvector_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pg_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin@gmail.com
    ports:
      - "5050:80"
    networks:
      - pg_network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./volumes/ollama_data:/root/.ollama
    networks:
      - webui_network
    devices:
      - /dev/dri:/dev/dri
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm

  webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports: 
      - "3000:8080"
    volumes:
      - ./volumes/webui_data:/app/backend/data
      - ./volumes/ollama_models:/ollama/models
    networks:
      - webui_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  webui_network:
    driver: bridge
  pg_network:
    driver: bridge

volumes:
  redis_data:
  webui_data:
  rabbitmq_data:
  pgvector_data:
  ollama_data:
  ollama_models:
